# Generated by Django 4.0.6 on 2022-07-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='estado',
            field=models.CharField(choices=[('0', 'Solicitado'), ('1', 'Pagado')], default='0', max_length=1),
        ),
    ]
