# Generated by Django 4.0.6 on 2022-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_pedidodetalle_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Solicitado'), ('1', 'Pagado')], default='0', max_length=1),
        ),
    ]
