f = open('alumnos.txt','w')
f.write('\nfher amable, fher@gmail.com,999999')
print("archivo creado con exito!!!")
f.write('\nana lopez, ana@gmail.com, 991919191')
f.write('\njorge perez, jorge@gmail.com, 92222222')
f.close()
fr = open('alumnos.txt','r')
dataAlumnos = fr.read()
print(dataAlumnos)
fr.close()

fa = open('alumnos.txt', 'a')
nombre = input("nombre : ")
email = input("email : ")
celular = input("celular : ")
fa.write("\n" + nombre + "," + email + "," + celular)
print("se registro el nuevo alumnos")