# Generated by Django 3.2 on 2022-07-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220713_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria_nombre',
            new_name='categoria_nom',
        ),
    ]
